### PR TITLE
Support `simpleCircle` rendering in `addGlPoints` via new `fragmentShader` parameter #53

### PR DESCRIPTION
**Pull request by AB-Kent**

### CODE REVIEW

**Comment by AB-Kent** [comment]
@tim-salabim Do you have any comment on this PR?

**Comment by tim-salabim** [comment]
Sorry for the silence. My plan is to use Christmas holidays to take care of all the loose ends. So likely not going to look at this before next week.

**Comment by AB-Kent** [comment]
OK, that's fine, thanks for letting me know!

Kent
________________________________

**Comment by tim-salabim** [comment]
@AB-Kent I've decided to utilise `...` to pass these (and other) arguments to the underlying JS function(s). I've tested this and think it works, but I would appreciate if you could test from your side too. Anyway, this now works for me:

```r
library(leaflet)
library(leafgl)
library(sf)

n = 1e5

df1 = data.frame(id = 1:n,
                 x = rnorm(n, 10, 1),
                 y = rnorm(n, 49, 0.8))
pts = st_as_sf(df1, coords = c("x", "y"), crs = 4326)

cols = topo.colors(nrow(pts))

leaflet() %>%
  addProviderTiles(provider = providers$CartoDB.DarkMatter) %>%
  addGlPoints(data = pts, fillColor = cols, popup = TRUE, fragmentShaderSource = "square")
```

image

I've also tested `simpleCircle` which also works for me. I couldn't get the other shader sources, e.g. 'dot' or 'puck' to work, but I don't see this as a pressing issue...

**Comment by AB-Kent** [comment]
Yes, this works great for me, thank you!!

**Pull request closed without merging**
